[project]
name = "fmi-course-python-project"
version = "0.1.0"
description = "Project workspace root"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.1.6",
    "db-util"
]

[tool.uv.sources]
db-util = { workspace = true }
db-models-shared = { workspace = true }
common-util = { workspace = true }
etl = { workspace = true }

[tool.uv.workspace]
members = [
    "libs/db-util",
    "libs/db-models-shared",
    "libs/common-util",
    "libs/etl",
    "services/app-server",
    "services/cli"
]


