# Generated by Django 5.1.6 on 2025-02-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='is_selected',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
