# Generated by Django 5.1.6 on 2025-02-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_symbol_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='irWebsite',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
