# Generated by Django 5.1.6 on 2025-02-16 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_symbol_irwebsite'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trackersymbols',
            unique_together={('symbol', 'tracker')},
        ),
        migrations.CreateModel(
            name='SymbolHistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('close_price', models.FloatField()),
                ('volume', models.FloatField()),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.symbol')),
            ],
            options={
                'ordering': ['timestamp'],
                'unique_together': {('symbol', 'timestamp')},
            },
        ),
    ]
