[project]
name = "app-server"
version = "0.1.0"
description = "Project application server"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "common-util",
    "db-models-shared",
    "db-util",
    "etl",
    "visualizer",
]

[tool.uv.sources]
db-util = { workspace = true }
common-util = { workspace = true }
etl = { workspace = true }
db-models-shared = { workspace = true }
visualizer = { workspace = true }

